In [4]:
import yaml
path = 'cam.yaml'
with open(path) as f:
    data = yaml.load(f)

cameras = data['Cameras']
cameras['Camera1']['Topics']['sub_image']

/tmp/ipykernel_3220/805454195.py:4: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)


'/usb_cam1/image_raw'

In [9]:
import camera
cameras = {}
for dic in data['Cameras']:
    print(dic)
    print(type(dic))


Camera1
<class 'str'>
Camera2
<class 'str'>


In [18]:
import rospy
help(rospy.Time.now())

ROSInitException: time is not initialized. Have you called init_node()?

In [19]:
import numpy as np
xyz = np.array([[1,2,3],[4,5,6],[1,3,4],[2,6,3]])
xyz

array([[1, 2, 3],
       [4, 5, 6],
       [1, 3, 4],
       [2, 6, 3]])

In [24]:
dis = np.sqrt(np.sum(xyz ** 2, axis=1))
dis

array([3.74165739, 8.77496439, 5.09901951, 7.        ])

In [25]:
distance = 8
a = dis[dis < distance]
a

array([3.74165739, 5.09901951, 7.        ])

In [53]:
x = np.c_[dis, dis].T.T
print(x)
for i in x:
    print(i, '\n')

[[3.74165739 3.74165739]
 [8.77496439 8.77496439]
 [5.09901951 5.09901951]
 [7.         7.        ]]
[3.74165739 3.74165739] 

[8.77496439 8.77496439] 

[5.09901951 5.09901951] 

[7. 7.] 



In [45]:
import math
theta = [math.radians(30), math.radians(60), math.radians(90)]
theta

[0.5235987755982988, 1.0471975511965976, 1.5707963267948966]

In [47]:
r_x = np.array([[1, 0, 0],
                [0, math.cos(theta[0]), -math.sin(theta[0])],
                [0, math.sin(theta[0]), math.cos(theta[0])]])

r_y = np.array([[math.cos(theta[1]), 0, math.sin(theta[1])],
                [0, 1, 0],
                [-math.sin(theta[1]), 0, math.cos(theta[1])]])

r_z = np.array([[math.cos(theta[2]), -math.sin(theta[2]), 0],
                [math.sin(theta[2]), math.cos(theta[2]), 0],
                [0, 0, 1]])

R1 = np.dot(r_x, np.dot(r_y, r_z))
print(R1)
R2 = np.dot(np.dot(r_z, r_y), r_x)
print(R2)

[[ 3.06161700e-17 -5.00000000e-01  8.66025404e-01]
 [ 8.66025404e-01 -4.33012702e-01 -2.50000000e-01]
 [ 5.00000000e-01  7.50000000e-01  4.33012702e-01]]
[[ 3.06161700e-17 -8.66025404e-01  5.00000000e-01]
 [ 5.00000000e-01  4.33012702e-01  7.50000000e-01]
 [-8.66025404e-01  2.50000000e-01  4.33012702e-01]]


In [60]:
u = xyz[:, 0]/xyz[:, 2]
v = xyz[:, 1]/xyz[:, 2]
np.c_[u,v].T.T

array([[0.33333333, 0.66666667],
       [0.66666667, 0.83333333],
       [0.25      , 0.75      ],
       [0.66666667, 2.        ]])